# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=0.4.0-alpha.1
maven_group=me.lingbopro
archives_name=lingbos-sussy-mod
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21
# Dependencies
architectury_api_version=13.0.8
fabric_loader_version=0.16.14
fabric_api_version=0.102.0+1.21
neoforge_version=21.0.167
